/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: b8a8ece0f8e8f9a5dabe0d6cfbf6a66e)
interface __BaseEnv_CloudflareEnv {
	RESEARCH_EXPORTS: R2Bucket;
	ASSETS: Fetcher;
	INLINE_JOBS: string;
	CODE_RUNNER_DRIVER: string;
	STORAGE_DRIVER: string;
	AUTH_LOCAL_ENABLED: string;
	WORKER_SELF_REFERENCE: Fetcher /* learn */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "INLINE_JOBS" | "CODE_RUNNER_DRIVER" | "STORAGE_DRIVER" | "AUTH_LOCAL_ENABLED">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}