import { bulk, DAY_MS, HOUR_MS, resetState, S } from "./state";
import type { SeedContext } from "./context";

const ANCHOR_AUDIT_ID = "audit_seed_anchor";

/**
 * Step 0 of the generated-data seed.
 *
 * 1. Resolves the time anchor. The first run stores `now` (floored to the hour) in an append-only AuditLog row
 *    (stable id); later runs reuse it, so re-running the seed reproduces identical timestamps and the append-only
 *    tables (AnalyticsEvent, LearningEvidence, AuditLog) stay consistent with the re-created transactional rows.
 *    All generated times are `anchor - N days (+ deterministic offsets)`. To refresh the dates, use a fresh database.
 * 2. Clears the rows generated by the modules below (reverse dependency order). Append-only tables are NOT cleared:
 *    their rows carry stable ids/idempotency keys and are inserted with skipDuplicates.
 */
export async function seedReset(ctx: SeedContext): Promise<void> {
  const p = ctx.prisma;
  resetState();

  const existing = await p.auditLog.findUnique({ where: { id: ANCHOR_AUDIT_ID } });
  let anchor: Date;
  const stored = (existing?.metadata as { anchor?: string } | null)?.anchor;
  if (stored) {
    anchor = new Date(stored);
  } else {
    anchor = new Date(Math.floor(Date.now() / HOUR_MS) * HOUR_MS);
    await bulk(
      p.auditLog,
      [
        {
          id: ANCHOR_AUDIT_ID,
          actorId: ctx.ids.users["admin"] ?? null,
          action: "seed.anchor",
          targetType: "seed",
          targetId: "dev-seed",
          reason: "Time anchor for deterministic synthetic data",
          metadata: {
            anchor: anchor.toISOString(),
            note: "generated data spans anchor-28d .. anchor",
          },
          createdAt: anchor,
        },
      ],
      { skipDuplicates: true },
    );
  }
  S.anchor = anchor;
  ctx.now = anchor;
  ctx.log(
    `time anchor: ${anchor.toISOString()} (${Math.round((Date.now() - anchor.getTime()) / DAY_MS)}d ago)`,
  );

  const courseIds = Object.values(ctx.ids.courses);
  const inCourses = { courseId: { in: courseIds } };
  await p.aiSession.deleteMany({ where: inCourses });
  await p.aiRequest.deleteMany({ where: { id: { startsWith: "aireq_" } } });
  await p.practiceSession.deleteMany({ where: inCourses });
  await p.codeRun.deleteMany({ where: { id: { startsWith: "run_" } } });
  await p.misconceptionObservation.deleteMany({ where: inCourses });
  await p.learnerTopicState.deleteMany({ where: inCourses });
  await p.courseAggregate.deleteMany({ where: inCourses });
  await p.assignmentAggregate.deleteMany({ where: inCourses });
  await p.questionAggregate.deleteMany({ where: inCourses });
  await p.topicAggregate.deleteMany({ where: inCourses });
  await p.misconceptionAggregate.deleteMany({ where: inCourses });
  await p.practiceItem.deleteMany({ where: inCourses });
  await p.misconception.deleteMany({ where: inCourses });
  await p.courseResource.deleteMany({ where: inCourses });
  await p.submission.deleteMany({ where: inCourses });
  await p.assignment.deleteMany({ where: inCourses });
  await p.socraPolicy.deleteMany({ where: inCourses });
  await p.learningObjective.deleteMany({ where: inCourses });
  await p.trainingCandidate.deleteMany({ where: { id: { startsWith: "tcand_" } } });
  await p.datasetVersion.deleteMany({ where: { id: { startsWith: "dsv_" } } });
  await p.researchExport.deleteMany({ where: { id: { startsWith: "rexp_" } } });
  await p.datasetManifest.deleteMany({ where: { id: { startsWith: "dsm_" } } });
  await p.backgroundJobFailure.deleteMany({ where: { id: { startsWith: "bjf_" } } });
}
